### ISSUE TITLE
not official download link and not over HTTPS

### ISSUE THREAD

**Issue by dimalinux** [dwmkerr/docker-dynamodb#15]
It would be nice if the Dockerfile was using the official download link.  Even if it was my own docker file downloading from my own S3 bucket, I wouldn't do it over HTTP.   Downloading executable content from a non-HTTPS protected link on the open Internet is like handing out free gifts to attackers.

**Comment by dwmkerr** [comment]
I actually struggled to find a download link I could hit directly, let me take a look again

**Comment by dwmkerr** [comment]
Fixed, thanks @dimalinux
