### ISSUE TITLE
support for AWS DynamoDB new On-Demand capacity mode missing

### ISSUE THREAD

**Issue by holtc** [dwmkerr/docker-dynamodb#25]
With the introduction of the AWS DynamoDB On-Demand capacity model at re:Invent 2018, table definitions have been changed. As a result, there are errors when trying to create tables using the `BillingMode=PAY_PER_REQUEST` param:

`Missing required key 'ProvisionedThroughput' in params`
`Unexpected key 'BillingMode' found in params`

**Expected Behaviour**
The local DynamoDB instance should allow capacity properties to be based on either 'ProvisionedThroughput' or 'BillingMode'.

**Steps to reproduce it**
Visit: [http://localhost:8000/shell](http://localhost:8000/shell) and try the following: 

```
var params = {
    TableName: 'table1',
    BillingMode: 'PAY_PER_REQUEST',
    KeySchema: [
        {
            AttributeName: 'id',
            KeyType: 'HASH',
        }
    ],
    AttributeDefinitions: [
        {
            AttributeName: 'id',
            AttributeType: 'S',
        }
    ],
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response

});
```

**Comment by XCarle** [comment]
:+1:

**Comment by dwmkerr** [comment]
OK here's the fix:

```
var params = {
    TableName: 'table1',
    ProvisionedThroughput: {
        ReadCapacityUnits: 1,
        WriteCapacityUnits: 1
    },
    KeySchema: [
        {
            AttributeName: 'id',
            KeyType: 'HASH',
        }
    ],
    AttributeDefinitions: [
        {
            AttributeName: 'id',
            AttributeType: 'S',
        }
    ],
};
dynamodb.createTable(params, function(err, data) {
    if (err) ppJson(err); // an error occurred
    else ppJson(data); // successful response

});
```

The issue is the underlying DynamoDB Local jar provided by AWS: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.UsageNotes.html

> Provisioned throughput settings are ignored in downloadable DynamoDB, even though the CreateTable operation requires them. For CreateTable, you can specify any numbers you want for provisioned read and write throughput, even though these numbers are not used. You can call UpdateTable as many times as you want per day. However, any changes to provisioned throughput values are ignored.

So it seems that specifying RCU/WCU values is now required, although the actual values are ignored. I will update the README now.
