### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by ivanjaros** [dwmkerr/docker-dynamodb#7]
Hi,
docker shows the image is running but if I try to open localhost:8000/shell it I cannot connect
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
326315035db0        dwmkerr/dynamodb    "java -jar DynamoDBL…"   10 minutes ago      Up 10 minutes       0.0.0.0:8000->8000/tcp   hardcore_nightingale
```

Any idea why that might be?

**Comment by dwmkerr** [comment]
Hmm that's a strange one - can you clone the repo and run:

```
make test
```

and share the output?

Also, are you on Windows/Mac/Linux and what is your docker version?

**Comment by ivanjaros** [comment]
Win10 + Docker Version 17.11.0-ce-win40 (14328) Channel: edge

**Comment by dwmkerr** [comment]
Try running:

```
docker-machine ip
```

Note down the IP, e.g, `192.168.13.14` then run open `http://192.168.13.14:8000`. On Windows, docker doesn't bind to `localhost` as the virtual machine is not as tightly integrated, so you'll probably need to hit the docker machine IP. Can you let me know if that works?

**Comment by ivanjaros** [comment]
`docker-machine ls` is empty but the container is running.

**Comment by dwmkerr** [comment]
Weird, can you show the output of:

```
docker container list
```

and then:

```
docker container inspect <name_of_dynamodb_container>
```

please? It might shed some light. I am trying to reproduce at the moment, but I am on a Mac. Docker isn't running in my Windows VM because I don't have the facility to run in nested virtualization mode (have to have a $50/year subscription for that feature, which is a pain). Am rooting out a PC to run the same test now...

**Comment by ivanjaros** [comment]
eeeh, my bad. I somehow ignored -p 8000:8000 when invoking the container.

**Comment by dwmkerr** [comment]
Ah OK no worries, glad it is sorted out!
