### ISSUE TITLE
Can't populate test data

### ISSUE THREAD

**Issue by bhavinp084** [dwmkerr/docker-dynamodb#9]
Hi mate,
Sorry but I'm new to dynamoDb and trying to setup docker environment for automation tests. As for that I need to setup test data which means creating table and setting up test data.

I can see that you mention use -dbPath /data but what I can't figure out is what format of files needs putting in /data folder ? Can you give example of one of those file to create data and populate some data ?

My docker compose looks like this:

toggle-dynamo-db:
      image: dwmkerr/dynamodb
      ports:
        - 3007:8000
      volumes:
        - ./toggle-dynamo-db:/opt/data

on local machine I use AWS CLI to populate data but as this docker container gone start from jenkins I can't run same command. I was hoping more info about /data folder and its files would help.

Thanks
Bhav

**Comment by dwmkerr** [comment]
Hi @bhavinp084,

Here's a few options.

*Create Test Data Dynamically*

Create the DynamoDB container as you are doing right now, then run a shell script which uses the `aws` cli to insert your data before running your tests:

```bash
# Create a table.
aws dynamodb --endpoint-url http://localhost:8000 --region us-east-1 \
	create-table \
	--table-name Supervillains \
    --attribute-definitions AttributeName=name,AttributeType=S \
	--key-schema AttributeName=name,KeyType=HASH \
	--provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1

# Add a record.
aws dynamodb --endpoint-url http://localhost:8000 --region us-east-1 \
    put-item \
    --table-name Supervillains \
    --item '{"name": {"S": "The Monarch"} }'
```

This is probably the easiest way to go. However, if you don't have the CLI on the box you need to run from, try this:

*Pre-Create Test Data*

Run up the container on your own machine, mounting a data directory just like you've done. Now on your machine, create the test data (assuming you can install the cli or anything else which can talk to dynamo). Now that this is done, stop the container.

At this point, you have a data directory which contains the raw data files for your test data. Now create a *new* docker image, based on my one, which has those data files you already created mounted into it. This new docker image is essentially your 'pre-baked' dynamodb image with your own data.

To help on the above, I've created a sample for you:

https://github.com/dwmkerr/docker-dynamodb/pull/10

---

Hopefully this helps! If so, please comment on this issue and I'll merge the PR and close the ticket.
